import { Opportunity } from '../src/types';

export const initialOpportunities: Opportunity[] = [
  // ==========================================
  // --- HACKATHONS (Global & India Vetted) ---
  // ==========================================
  {
    id: 'hack-amazon-ml-2026',
    category: 'hackathon',
    name: "Amazon ML Challenge 2026",
    organization: 'Amazon',
    logoUrl: 'https://images.unsplash.com/photo-1523474255658-4af61b168344?w=128&auto=format&fit=crop&q=80',
    description: "72-hour intensive machine learning competition challenging student and developer teams to build cutting-edge predictive models and NLP systems on Amazon's real customer datasets.",
    officialUrl: 'https://unstop.com/hackathons/amazon-ml-challenge-2026-amazon-1743604',
    registrationUrl: 'https://unstop.com/hackathons/amazon-ml-challenge-2026-amazon-1743604',
    startDate: '2026-09-22',
    endDate: '2026-09-25',
    deadline: '2026-09-20',
    location: 'Online / Virtual',
    mode: 'online',
    geography: 'national',
    domains: ['AI/ML', 'Data Science'],
    skills: ['Python', 'Machine Learning', 'NLP', 'Deep Learning', 'PyTorch'],
    eligibility: 'Open to engineering, science, and technology students across India. Teams of 1-4 members.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'Unstop Official Listing',
    featured: true,
    teamSize: '1-4 Members',
    prizePool: '₹1,00,000 + AWS Credits',
    competitionType: 'Machine Learning Challenge',
    bookmarksCount: 342,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-build-with-bharat-3',
    category: 'hackathon',
    name: 'Build With Bharat 3.0',
    organization: 'CodeVerse × Chitkara University',
    logoUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=128&auto=format&fit=crop&q=80',
    description: 'National-level 24-hour hackathon with open tracks in AI, Web3, Cloud, and IoT in collaboration with ACM Student Chapter and NEP Cell.',
    officialUrl: 'https://unstop.com/hackathons/build-with-bharat-30-chitkara-university-cu-himachal-pradesh-1722484',
    registrationUrl: 'https://unstop.com/o/8Nn5gTC?lb=logged_out_user&utm_medium=Share&utm_source=WhatsApp',
    startDate: '2026-09-21',
    endDate: '2026-09-22',
    deadline: '2026-09-18',
    location: 'Chitkara University, Himachal Pradesh, India',
    mode: 'offline',
    geography: 'national',
    domains: ['AI/ML', 'Web3', 'Cloud Computing', 'IoT'],
    skills: ['Any Stack', 'AI', 'Full Stack', 'Cloud', 'IoT'],
    eligibility: 'Undergraduate and postgraduate students across India. Individual or team participation.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'Unstop & WhatsApp Community',
    featured: true,
    teamSize: '2-5 Members',
    prizePool: '₹40,00,000',
    competitionType: 'National Hackathon',
    bookmarksCount: 188,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-revenuecat-shipaton',
    category: 'hackathon',
    name: 'RevenueCat Shipaton 2026',
    organization: 'RevenueCat',
    logoUrl: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=128&auto=format&fit=crop&q=80',
    description: 'Ship a real iOS, Android, or macOS app incorporating RevenueCat in-app purchases or subscriptions for cash prizes, a sponsored trip to NYC, and Times Square billboard feature.',
    officialUrl: 'https://revenuecat-shipaton-2026.devpost.com/',
    registrationUrl: 'https://www.shipaton.com/',
    startDate: '2026-09-01',
    endDate: '2026-09-30',
    deadline: '2026-09-30',
    location: 'Online / Global',
    mode: 'online',
    geography: 'international',
    domains: ['Mobile Development', 'AI/ML', 'Software Development'],
    skills: ['iOS', 'Android', 'Flutter', 'React Native', 'Swift', 'RevenueCat SDK'],
    eligibility: 'Global; individuals or teams; Next Gen category specifically for students aged 13+.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Devpost Official',
    featured: true,
    teamSize: 'Solo or Teams (No Limit)',
    prizePool: '$740,000+ Cash Prizes + NYC Trip',
    competitionType: 'App Shipathon',
    bookmarksCount: 512,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-hacker-house-goa',
    category: 'hackathon',
    name: 'Hacker House Goa 2026',
    organization: '2:47PM Studio × Devfolio',
    logoUrl: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=128&auto=format&fit=crop&q=80',
    description: 'AI × Crypto Builder Residency & Hacker House in Goa. Ship a real AI × Web3 product with multichain architecture, autonomous AI agents, and production smart contracts.',
    officialUrl: 'https://hacker-house-goa-2026.devfolio.co/overview',
    registrationUrl: 'https://hacker-house-goa-2026.devfolio.co/',
    startDate: '2026-10-28',
    endDate: '2026-10-31',
    deadline: '2026-10-01',
    location: 'Goa, India',
    mode: 'offline',
    geography: 'national',
    domains: ['Web3', 'AI/ML', 'Blockchain', 'Agentic AI'],
    skills: ['Solidity', 'AI Agents', 'Ethereum', 'Smart Contracts', 'Web3.js'],
    eligibility: 'Developers, students, and Web3 builders. Free registration with curated cohort selection.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Devfolio Official',
    featured: true,
    teamSize: '1-3 Members',
    prizePool: '$50,000+ Bounties',
    competitionType: 'Builder Residency / Hacker House',
    bookmarksCount: 295,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-ethglobal-mumbai',
    category: 'hackathon',
    name: 'ETHGlobal Mumbai 2026',
    organization: 'ETHGlobal',
    logoUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=128&auto=format&fit=crop&q=80',
    description: 'Ethereum and Web3 build weekend bringing together developers, cryptographic researchers, and founders across DeFi, Zero-Knowledge proofs, and AI×Crypto.',
    officialUrl: 'https://ethglobal.com/events/mumbai',
    registrationUrl: 'https://ethglobal.com/events/mumbai',
    startDate: '2026-11-05',
    endDate: '2026-11-07',
    deadline: '2026-10-15',
    location: 'Mumbai, India',
    mode: 'offline',
    geography: 'international',
    domains: ['Web3', 'Blockchain', 'FinTech', 'AI/ML'],
    skills: ['Solidity', 'Web3', 'EVM', 'Rust', 'Next.js'],
    eligibility: 'Open to builders, students, and Web3 engineers globally. Free application.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'ETHGlobal Portal',
    featured: true,
    teamSize: '1-5 Members',
    prizePool: '$150,000+ in Bounties & Partner Prizes',
    competitionType: 'Web3 Hackathon',
    bookmarksCount: 420,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-nebius-nvidia',
    category: 'hackathon',
    name: 'Nebius × NVIDIA Global AI Hackathon',
    organization: 'Nebius & NVIDIA',
    logoUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=128&auto=format&fit=crop&q=80',
    description: 'Build production-ready GenAI apps, autonomous agents, and scalable model pipelines deployed on NVIDIA GPUs and Nebius AI Cloud infrastructure.',
    officialUrl: 'https://nebiusglobalaihackathon.devpost.com/',
    registrationUrl: 'https://nebiusglobalaihackathon.devpost.com/',
    startDate: '2026-09-15',
    endDate: '2026-10-30',
    deadline: '2026-10-30',
    location: 'Online / Global',
    mode: 'online',
    geography: 'international',
    domains: ['AI/ML', 'Cloud Computing', 'Data Science'],
    skills: ['GenAI', 'AI Agents', 'CUDA', 'Python', 'PyTorch', 'GPU Deployment'],
    eligibility: 'Open globally to developers, students, and AI researchers. 18+.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Devpost Official',
    featured: true,
    teamSize: '1-4 Members',
    prizePool: '$50,000 Total Cash & GPU Credits',
    competitionType: 'AI Hackathon',
    bookmarksCount: 380,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-amazon-build-ship-shape',
    category: 'hackathon',
    name: 'Amazon Developer Hackathon — Build, Ship, Shape',
    organization: 'Amazon',
    logoUrl: 'https://images.unsplash.com/photo-1523474255658-4af61b168344?w=128&auto=format&fit=crop&q=80',
    description: 'Build novel applications and AI agent workflows for Fire TV, Alexa+, Ring, and AWS smart ambient devices using modern agentic toolkits.',
    officialUrl: 'https://amazonappdev2026.devpost.com/',
    registrationUrl: 'https://amazonappdev2026.devpost.com/',
    startDate: '2026-09-01',
    endDate: '2026-10-23',
    deadline: '2026-10-23',
    location: 'Online / Global',
    mode: 'online',
    geography: 'international',
    domains: ['AI/ML', 'IoT', 'Cloud Computing', 'Voice AI'],
    skills: ['AI Agents', 'MCP', 'AWS', 'Alexa Skills Kit', 'Node.js', 'Python'],
    eligibility: '18+ / legal age; open globally subject to official terms.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Devpost Official',
    featured: false,
    teamSize: '1-5 Members',
    prizePool: '$190,000 Cash + AWS Credits',
    competitionType: 'Developer Challenge',
    bookmarksCount: 260,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-serpapi-india',
    category: 'hackathon',
    name: 'SerpApi India Hackathon 2026',
    organization: 'SerpApi',
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    description: '35-day online hackathon across 6 tracks (AI Agents, Open-Source Integrations, Travel & Local Discovery, Commerce, Knowledge). Every project makes meaningful use of SerpApi live search data.',
    officialUrl: 'https://serpapi.github.io/serpapi-india-hackathon-2026/',
    registrationUrl: 'https://serpapi.github.io/serpapi-india-hackathon-2026/',
    startDate: '2026-09-01',
    endDate: '2026-10-05',
    deadline: '2026-10-05',
    location: 'Online, India',
    mode: 'online',
    geography: 'national',
    domains: ['AI/ML', 'Data Science', 'Web Development', 'Open Source'],
    skills: ['RAG', 'LLM Apps', 'Python', 'TypeScript', 'SerpApi', 'Search Data'],
    eligibility: 'Indian residents aged 18+. Any programming language or tech stack allowed.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'SerpApi Official GitHub',
    featured: false,
    teamSize: '1-5 Members (Individual Allowed)',
    prizePool: '₹3,00,000+ in Total Prize Value',
    competitionType: 'Asynchronous Hackathon',
    bookmarksCount: 215,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-nasa-space-apps',
    category: 'hackathon',
    name: 'NASA Space Apps Challenge 2026',
    organization: 'NASA & International Space Agencies',
    logoUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=128&auto=format&fit=crop&q=80',
    description: 'The premier global space & science hackathon utilizing open NASA satellite, climate, and deep-space telemetry data to address pressing challenges on Earth and in space.',
    officialUrl: 'https://www.spaceappschallenge.org/',
    registrationUrl: 'https://www.spaceappschallenge.org/2026/',
    startDate: '2026-11-14',
    endDate: '2026-11-15',
    deadline: '2026-10-15',
    location: 'Global (Local Chapters + Online)',
    mode: 'hybrid',
    geography: 'international',
    domains: ['AI/ML', 'Data Science', 'Robotics', 'Space Tech'],
    skills: ['GIS', 'Python', 'Computer Vision', 'Data Visualization', 'Earth Science'],
    eligibility: 'Open to all ages, skills, and backgrounds worldwide. Free entry.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'NASA Space Apps Official',
    featured: true,
    teamSize: '2-6 Members',
    prizePool: 'Global NASA Winner Awards & Launch Site Invitation',
    competitionType: 'Global Hackathon',
    bookmarksCount: 490,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-esa-euclid',
    category: 'hackathon',
    name: 'ESA Euclid Hackathon 2026',
    organization: 'European Space Agency (ESA) Datalabs',
    logoUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=128&auto=format&fit=crop&q=80',
    description: 'Develop machine learning and computer vision algorithms on Euclid space mission astronomical survey datasets at ESAC in Madrid.',
    officialUrl: 'https://www.cosmos.esa.int/web/esa-datalabs-euclid-hackathon-2026/home',
    registrationUrl: 'https://www.cosmos.esa.int/web/esa-datalabs-euclid-hackathon-2026/home',
    startDate: '2026-11-23',
    endDate: '2026-11-26',
    deadline: '2026-10-15',
    location: 'ESAC, Madrid, Spain',
    mode: 'offline',
    geography: 'international',
    domains: ['Data Science', 'AI/ML', 'Research', 'Space Tech'],
    skills: ['Python', 'Machine Learning', 'Computer Vision', 'Astrophysics', 'Astropy'],
    eligibility: 'Students, researchers, and data scientists internationally.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'ESA Cosmos Official',
    featured: false,
    teamSize: '1-4 Members',
    prizePool: 'ESA Sponsored Travel & Hardware Grants',
    competitionType: 'Astrophysics Hackathon',
    bookmarksCount: 175,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-hackodisha-6',
    category: 'hackathon',
    name: 'HackOdisha 6.0',
    organization: 'Webwiz, NIT Rourkela',
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    description: '36-hour flagship hackathon connecting 5,000+ developers, beginners, and experienced builders across technology, real-world problem-solving, AI, and Web3.',
    officialUrl: 'https://www.hackodisha.dev/',
    registrationUrl: 'https://www.hackodisha.dev/',
    startDate: '2026-10-31',
    endDate: '2026-11-01',
    deadline: '2026-10-30',
    location: 'NIT Rourkela / Online',
    mode: 'online',
    geography: 'national',
    domains: ['Web Development', 'AI/ML', 'Web3', 'Open Innovation'],
    skills: ['Full-stack', 'AI', 'React', 'Node.js', 'Python'],
    eligibility: 'Open to developers, students, and experienced builders. Free entry.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Webwiz Official',
    featured: false,
    teamSize: '1-5 Members (Individual Allowed)',
    prizePool: '₹55,000+ Cash + Swag & Bounties',
    competitionType: '36-Hour Hackathon',
    bookmarksCount: 230,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-code-cubicle-6',
    category: 'hackathon',
    name: 'Code Cubicle 6.0',
    organization: 'Geek Room',
    logoUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=128&auto=format&fit=crop&q=80',
    description: 'Hybrid hackathon featuring an online round and a 7-hour offline finale at the Paytm Office in Noida across AI, software engineering, and emerging tech tracks.',
    officialUrl: 'https://hackculture.io/hackathons/code-cubicle-6-0',
    registrationUrl: 'https://hackculture.io/hackathons/code-cubicle-6-0',
    startDate: '2026-10-03',
    endDate: '2026-10-11',
    deadline: '2026-09-20',
    location: 'Paytm Office, Noida, Uttar Pradesh',
    mode: 'hybrid',
    geography: 'national',
    domains: ['AI/ML', 'Software Development', 'Web Development'],
    skills: ['Full-stack', 'AI', 'n8n', 'Python', 'React'],
    eligibility: 'Students, developers, engineers, and AI builders. Free entry.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'Geek Room & HackCulture',
    featured: false,
    teamSize: '1-4 Members',
    prizePool: '$20,000+ in Prizes, n8n Licenses & Cash',
    competitionType: 'Hybrid Hackathon',
    bookmarksCount: 198,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-hack-with-hyderabad-3',
    category: 'hackathon',
    name: 'Hack With Hyderabad 3.0',
    organization: 'Devnovate × Hack With India',
    logoUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=128&auto=format&fit=crop&q=80',
    description: '8-hour rapid in-person coding challenge hosted at the Microsoft Office in Hyderabad with $99 dev credits and direct internship/PPO opportunities for top performers.',
    officialUrl: 'https://devnovate.co/event/hack-with-hyderabad-30',
    registrationUrl: 'https://devnovate.co/event/hack-with-hyderabad-30',
    startDate: '2026-10-05',
    endDate: '2026-10-05',
    deadline: '2026-10-02',
    location: 'Microsoft Office, Hyderabad, Telangana',
    mode: 'offline',
    geography: 'regional',
    domains: ['AI/ML', 'Software Development', 'Open Innovation'],
    skills: ['Python', 'React', 'Cloud', 'Algorithms', 'AI'],
    eligibility: 'Students, developers, creators & tech enthusiasts across India.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Devnovate Official',
    featured: false,
    teamSize: '2-6 Members',
    prizePool: '$2,000 + $99 Dev Credits + Internship/PPO Exposure',
    competitionType: 'Rapid Coding Hackathon',
    bookmarksCount: 165,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-hackharvard-2026',
    category: 'hackathon',
    name: 'HackHarvard 2026',
    organization: 'Harvard University',
    logoUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=128&auto=format&fit=crop&q=80',
    description: '36-hour premier collegiate hackathon hosted inside Harvard University’s Science and Engineering Complex focusing on AI, healthcare, sustainability, and civic technologies.',
    officialUrl: 'https://hhuh.io/',
    registrationUrl: 'https://share.google/DFeb93OlKO58jW6Tg',
    startDate: '2026-10-16',
    endDate: '2026-10-18',
    deadline: '2026-09-25',
    location: 'Science and Engineering Complex, Harvard University, Cambridge, MA, USA',
    mode: 'offline',
    geography: 'international',
    domains: ['AI/ML', 'Healthcare', 'Software Development', 'Open Innovation'],
    skills: ['Python', 'TypeScript', 'React', 'Mobile Apps', 'AI'],
    eligibility: 'Undergraduate students globally. Free for accepted participants.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'HackHarvard Student Org',
    featured: true,
    teamSize: '1-4 Members',
    prizePool: '$30,000+ Cash, Bounties & Hardware',
    competitionType: 'Collegiate Hackathon',
    bookmarksCount: 375,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-hackfront-india-2026',
    category: 'hackathon',
    name: 'hackFront India 2026',
    organization: 'Where U Elevate',
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80',
    description: '20-week national innovation league spanning 5 talent hubs (Delhi NCR, Mumbai, Bengaluru, Hyderabad, Kolkata) with a 36-hour offline national finale in Delhi across 8 frontier themes.',
    officialUrl: 'https://whereuelevate.com/drills',
    registrationUrl: 'https://hackfrontindia.tech/',
    startDate: '2026-10-20',
    endDate: '2027-02-15',
    deadline: '2026-10-15',
    location: 'Hybrid (5 Regional Hubs + Delhi Finale)',
    mode: 'hybrid',
    geography: 'national',
    domains: ['AI/ML', 'FinTech', 'Cybersecurity', 'Open Source', 'EV & Mobility'],
    skills: ['AI', 'Cybersecurity', 'FinTech', 'Telecom', 'Green Energy'],
    eligibility: 'Students and early-career builders across India. Free registration.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Where U Elevate',
    featured: true,
    teamSize: '2-5 Members',
    prizePool: '₹1 Crore+ in Prizes, Incubation & Hiring',
    competitionType: 'National Innovation League',
    bookmarksCount: 410,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-kaya-ai-youth-2026',
    category: 'hackathon',
    name: 'KAYA: Artificial Intelligence Youth Exploration 2026',
    organization: 'AZMTH × CIIE, I3F, IIT (BHU) Varanasi',
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    description: 'AI & emerging technology festival featuring online qualification and an offline finale at Swatantrata Bhavan, CIIE, I3F, IIT (BHU) Varanasi.',
    officialUrl: 'https://kaya.azmth.in/register?ref=KCA-2031',
    registrationUrl: 'https://kaya.azmth.in/register?ref=KCA-2031',
    startDate: '2026-10-10',
    endDate: '2026-10-11',
    deadline: '2026-09-20',
    location: 'Swatantrata Bhavan, IIT (BHU) Varanasi, India',
    mode: 'hybrid',
    geography: 'national',
    domains: ['AI/ML', 'Data Science', 'Open Innovation'],
    skills: ['Python', 'Deep Learning', 'Computer Vision', 'Generative AI'],
    eligibility: 'Students, professionals, entrepreneurs, creators, researchers, and hobbyists.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'AZMTH & IIT (BHU) CIIE',
    featured: false,
    teamSize: 'Individual or Teams',
    prizePool: '₹2,50,000+ Incubation & Awards',
    competitionType: 'AI Festival & Competition',
    bookmarksCount: 145,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-build-with-ai-communities-2',
    category: 'hackathon',
    name: 'Build with AI: Code for Communities (Second Edition)',
    organization: 'Google Developer Groups (GDG) India × Hack2Skill',
    logoUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=128&auto=format&fit=crop&q=80',
    description: 'National-level AI hackathon powered by Google Cloud focusing on building scalable Gemini solutions for governance, climate, healthcare, and agriculture.',
    officialUrl: 'https://hack2skill.com/event/codeforcommunities2',
    registrationUrl: 'https://hack2skill.com/event/codeforcommunities2',
    startDate: '2026-10-05',
    endDate: '2026-10-25',
    deadline: '2026-09-30',
    location: 'Hybrid / India',
    mode: 'hybrid',
    geography: 'national',
    domains: ['AI/ML', 'Cloud Computing', 'Healthcare', 'Open Innovation'],
    skills: ['Gemini API', 'Google Cloud', 'Generative AI', 'Python', 'Vertex AI'],
    eligibility: 'Developers, students, AI/ML practitioners across India. Free registration.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'GDG India & Hack2Skill',
    featured: true,
    teamSize: '1-4 Members',
    prizePool: '₹5,00,000+ Google Cloud Credits & Cash',
    competitionType: 'Google Cloud Hackathon',
    bookmarksCount: 320,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-hacker-ring-2',
    category: 'hackathon',
    name: 'Hacker-Ring 2.0',
    organization: 'RVITM Bengaluru (ECE, CSE AI/ML & GDG)',
    logoUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=128&auto=format&fit=crop&q=80',
    description: '36-hour national-level hybrid hackathon featuring Voice AI, Agentic AI, and Open Hardware tracks with online shortlisting and offline finals.',
    officialUrl: 'https://hackering.netlify.app/',
    registrationUrl: 'https://hackering.netlify.app/',
    startDate: '2026-10-08',
    endDate: '2026-10-10',
    deadline: '2026-09-28',
    location: 'RVITM, J.P. Nagar 8th Phase, Bengaluru, Karnataka',
    mode: 'hybrid',
    geography: 'regional',
    domains: ['AI/ML', 'Web Development', 'Robotics', 'Voice AI'],
    skills: ['Voice AI', 'Agentic AI', 'IoT', 'Python', 'Full Stack'],
    eligibility: 'Student developers, hardware engineers, and AI researchers.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'RVITM Official',
    featured: false,
    teamSize: '2-4 Members',
    prizePool: '₹1,00,000',
    competitionType: '36-Hour Hackathon',
    bookmarksCount: 135,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-pixels-to-products',
    category: 'hackathon',
    name: 'Pixels to Products: Cloudinary AI Hackathon 2026',
    organization: 'HackIndia × Cloudinary',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    description: 'Build AI-powered media products, generative content workflows, and media transformation pipelines leveraging Cloudinary APIs.',
    officialUrl: 'https://hackindia.org/2026/pixels-to-products-cloudinary-ai-hackathon-2026',
    registrationUrl: 'https://hackindia.org/2026/pixels-to-products-cloudinary-ai-hackathon-2026',
    startDate: '2026-09-10',
    endDate: '2026-10-03',
    deadline: '2026-10-03',
    location: 'Online / Virtual',
    mode: 'online',
    geography: 'national',
    domains: ['AI/ML', 'Web Development', 'Data Science'],
    skills: ['Cloudinary API', 'Generative AI', 'React', 'Python', 'Next.js'],
    eligibility: 'Developers, designers, and builders across India. All experience levels.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'HackIndia Official',
    featured: false,
    teamSize: '1-4 Members',
    prizePool: '₹1,40,000 Total Cash',
    competitionType: 'Media AI Hackathon',
    bookmarksCount: 155,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-fund-my-crazy',
    category: 'hackathon',
    name: 'Fund My Crazy 2026',
    organization: 'Google Gemini / GSA IIT Guwahati',
    logoUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=128&auto=format&fit=crop&q=80',
    description: 'Gemini-powered challenge across transport, community, healthcare, and education featuring ₹1 Crore+ cash pool, Pixel 10a devices, and sponsored IIT Guwahati trip.',
    officialUrl: 'https://fundmycrazy.com/index.html',
    registrationUrl: 'https://fundmycrazy.com/index.html',
    startDate: '2026-09-01',
    endDate: '2026-10-05',
    deadline: '2026-09-20',
    location: 'Online / IIT Guwahati',
    mode: 'hybrid',
    geography: 'international',
    domains: ['AI/ML', 'Healthcare', 'Web Development', 'Open Innovation'],
    skills: ['Gemini API', 'AI Agents', 'Full Stack', 'Python', 'Mobile'],
    eligibility: '13+; students; open internationally subject to restrictions.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'GSA IITG Official',
    featured: true,
    teamSize: '1-4 Members',
    prizePool: '₹1 Crore+ Cash + Pixel 10a + IIT Trip',
    competitionType: 'AI Innovation Challenge',
    bookmarksCount: 460,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-ibm-z-datathon',
    category: 'hackathon',
    name: 'IBM Z Datathon 2026',
    organization: 'IBM & Shooting Stars Foundation',
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    description: 'Build impactful AI and data applications on IBM Z enterprise hardware and LinuxONE for social good.',
    officialUrl: 'https://www.starhacks.org/ibm-z-datathon-2026',
    registrationUrl: 'https://www.starhacks.org/ibm-z-datathon-2026',
    startDate: '2026-09-10',
    endDate: '2026-10-15',
    deadline: '2026-10-01',
    location: 'Hybrid / Global',
    mode: 'hybrid',
    geography: 'international',
    domains: ['AI/ML', 'Cloud Computing', 'Data Science'],
    skills: ['Data Science', 'AI on IBM Z', 'LinuxONE', 'Python', 'SQL'],
    eligibility: 'Undergraduate and graduate students globally, 18+.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'IBM StarHacks',
    featured: false,
    teamSize: '1-4 Members',
    prizePool: '$50,000 Cash',
    competitionType: 'Enterprise AI Datathon',
    bookmarksCount: 205,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-robofest-gujarat-3',
    category: 'hackathon',
    name: 'Robofest Gujarat 3.0',
    organization: 'GUJCOST, Dept. of Science & Technology, Govt. of Gujarat',
    logoUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=128&auto=format&fit=crop&q=80',
    description: 'State-backed robotics and embodied AI championship featuring autonomous rovers, swarm robotics, underwater bots, and hexapods with ₹5 Crore total funding.',
    officialUrl: 'https://robofest.gujarat.gov.in/',
    registrationUrl: 'https://robofest.gujarat.gov.in/',
    startDate: '2026-09-25',
    endDate: '2026-11-20',
    deadline: '2026-09-20',
    location: 'Gujarat, India',
    mode: 'hybrid',
    geography: 'national',
    domains: ['Robotics', 'AI/ML', 'IoT'],
    skills: ['ROS', 'Robotics', 'Computer Vision', 'Embedded C', 'Hardware'],
    eligibility: 'School & college students nationwide. Teams of 2-5 members.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'GUJCOST Official',
    featured: false,
    teamSize: '2-5 Members',
    prizePool: '₹5 Crore Total Pool & Incubation',
    competitionType: 'Robotics Championship',
    bookmarksCount: 270,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'hack-agentic-cinema',
    category: 'hackathon',
    name: 'Agentic Cinema: The Blockbuster Hackathon',
    organization: 'Google Cloud, IBM, Grafana Labs, ClickHouse, Replit',
    logoUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=128&auto=format&fit=crop&q=80',
    description: 'Build functional agents using Gemini + Google Cloud Agent Builder integrating MCP and partner infrastructure to solve real media & entertainment workflows.',
    officialUrl: 'https://agentic-cinema.devpost.com/',
    registrationUrl: 'https://agentic-cinema.devpost.com/',
    startDate: '2026-09-01',
    endDate: '2026-09-25',
    deadline: '2026-09-25',
    location: 'Online / Global',
    mode: 'online',
    geography: 'international',
    domains: ['AI/ML', 'Cloud Computing', 'Software Development'],
    skills: ['Gemini', 'Google Agent Builder', 'MCP', 'ClickHouse', 'Replit'],
    eligibility: '18+ legal age; open to developers globally including India.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Devpost Official',
    featured: false,
    teamSize: '1-4 Members',
    prizePool: '$75,000 Cash ($15,000 per partner track)',
    competitionType: 'AI Agent Hackathon',
    bookmarksCount: 310,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },

  // ===============================================
  // --- TECH INTERNSHIPS (Competitive & Vetted) ---
  // ===============================================
  {
    id: 'intern-max-planck-cis-2026',
    category: 'internship',
    name: 'Max Planck CIS Research Internship 2026–2027',
    organization: 'Max Planck Institute for Software Systems & CIS',
    logoUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=128&auto=format&fit=crop&q=80',
    description: 'Fully funded research internship in Germany working alongside faculty and research scientists on frontier challenges in AI, Machine Learning, Systems, Security, and Computer Vision.',
    officialUrl: 'https://www.cis.mpg.de/internships/',
    registrationUrl: 'https://www.cis.mpg.de/internships/',
    startDate: '2027-05-01',
    endDate: '2027-08-31',
    deadline: '2026-11-01',
    location: 'Saarbrücken & Kaiserslautern, Germany',
    mode: 'offline',
    geography: 'international',
    domains: ['AI/ML', 'Research', 'Software Development', 'Cybersecurity'],
    skills: ['C++', 'Python', 'Distributed Systems', 'Machine Learning', 'Formal Verification'],
    eligibility: 'Undergraduate, Master’s, and pre-doctoral students with exceptional academic standing in CS or related disciplines.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Max Planck Official',
    featured: true,
    role: 'Research Intern (Systems, ML & Vision)',
    duration: '10–14 Weeks',
    stipend: '€1,200/month + Full Travel & Housing Reimbursement',
    paidType: 'paid',
    institution: 'Max Planck Institute',
    bookmarksCount: 430,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'intern-snapdragon-ai-lab',
    category: 'internship',
    name: 'Snapdragon AI Lab Build & Present Challenge',
    organization: 'Qualcomm',
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    description: 'Develop optimized on-device AI applications for Snapdragon X-series powered PCs. Top winners receive Qualcomm R&D internship offers, HP OmniBook Ultra hardware, and executive mentorship.',
    officialUrl: 'https://unstop.com/competitions/snapdragon-ai-lab-build-present-challenge-qualcomm-1740000',
    registrationUrl: 'https://unstop.com/competitions/snapdragon-ai-lab-build-present-challenge-qualcomm-1740000',
    startDate: '2026-09-01',
    endDate: '2026-10-15',
    deadline: '2026-09-30',
    location: 'Online / India',
    mode: 'online',
    geography: 'national',
    domains: ['AI/ML', 'Software Development', 'Robotics'],
    skills: ['Qualcomm AI Hub', 'ONNX', 'Python', 'Edge AI', 'NPU Acceleration'],
    eligibility: 'Indian residents aged 18+; engineering, data science, and CS students.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Unstop Official Qualcomm Listing',
    featured: true,
    role: 'Qualcomm AI Engineering Intern Track',
    duration: 'Summer Internship',
    stipend: 'Qualcomm R&D Internship + HP OmniBook Ultra',
    paidType: 'paid',
    institution: 'Qualcomm R&D India',
    bookmarksCount: 310,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'intern-yuva-yodha-schneider',
    category: 'internship',
    name: 'Yuva Yodha Energy Tech Challenge',
    organization: 'Schneider Electric',
    logoUrl: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=128&auto=format&fit=crop&q=80',
    description: 'Energy and renewables engineering competition offering ₹45 Lakh in prizes, SE Ventures incubation, and Top 10 pre-placement interviews (PPO / full-time internship placements).',
    officialUrl: 'https://www.yuvayodhatech.com/',
    registrationUrl: 'https://www.yuvayodhatech.com/',
    startDate: '2026-09-15',
    endDate: '2026-10-25',
    deadline: '2026-10-04',
    location: 'Online → Finale in India',
    mode: 'hybrid',
    geography: 'national',
    domains: ['AI/ML', 'IoT', 'CleanTech', 'Robotics'],
    skills: ['Smart Grids', 'IoT', 'Renewable Tech', 'Python', 'Embedded Systems'],
    eligibility: 'Indian citizens 18+; full-time students in STEM/Engineering disciplines across India.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Schneider Electric Official',
    featured: false,
    role: 'Energy Tech Intern / Pre-Placement Offer (PPO)',
    duration: '6 Months',
    stipend: 'Competitive Corporate Internship & Pre-Placement Offer',
    paidType: 'paid',
    institution: 'Schneider Electric',
    bookmarksCount: 220,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },

  // =========================================================
  // --- RESEARCH FELLOWSHIPS & SYMPOSIUMS (Vetted Grants) ---
  // =========================================================
  {
    id: 'research-incis-2027-iitm',
    category: 'research',
    name: 'InCIS 2027 Research Conference',
    organization: 'Department of Management Studies, IIT Madras',
    logoUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=128&auto=format&fit=crop&q=80',
    description: 'Premier research paper submission track on artificial intelligence, algorithmic governance, data protection, cybersecurity, and national digital infrastructure.',
    officialUrl: 'https://doms.iitm.ac.in/incis2027/',
    registrationUrl: 'https://doms.iitm.ac.in/incis2027/',
    startDate: '2027-03-10',
    endDate: '2027-03-12',
    deadline: '2026-09-30',
    location: 'IIT Madras, Chennai, India',
    mode: 'hybrid',
    geography: 'national',
    domains: ['Research', 'AI/ML', 'Cybersecurity', 'Data Science'],
    skills: ['Academic Writing', 'Empirical Research', 'Data Governance', 'AI Policy'],
    eligibility: 'Researchers, Ph.D. scholars, Master’s, and undergraduate researchers.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'IIT Madras DoMS',
    featured: true,
    researchArea: 'AI, Data Governance, Information Systems & Cybersecurity',
    institution: 'IIT Madras',
    funding: 'Conference Best Paper Award & Springer Publication',
    positionType: 'Paper Presentation & Fellowship',
    bookmarksCount: 215,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'research-iris-2027-iitm',
    category: 'research',
    name: 'IRIS 2027 Research Symposium',
    organization: 'Shaastra, IIT Madras',
    logoUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=128&auto=format&fit=crop&q=80',
    description: 'Undergraduate research symposium calling for high-impact research papers in Computer Vision, Autonomous Robotics, and Embodied Deep Learning with IEEE co-publication.',
    officialUrl: 'https://iris.shaastra.org/',
    registrationUrl: 'https://iris.shaastra.org/',
    startDate: '2027-01-03',
    endDate: '2027-01-06',
    deadline: '2026-10-01',
    location: 'IIT Madras, Chennai, India',
    mode: 'hybrid',
    geography: 'national',
    domains: ['Research', 'Robotics', 'AI/ML'],
    skills: ['Computer Vision', 'Robotics', 'PyTorch', 'ROS', 'Mathematical Modeling'],
    eligibility: 'Undergraduate and graduate student researchers in engineering and computer science.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Shaastra IIT Madras',
    featured: true,
    researchArea: 'Computer Vision, Robotics & Embodied AI',
    institution: 'IIT Madras',
    funding: '₹1,50,000 Grants & IEEE Co-Publication',
    positionType: 'Symposium Fellow',
    bookmarksCount: 195,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'research-climx-kaggle',
    category: 'research',
    name: 'ClimX Extreme Climate ML Challenge',
    organization: 'Kaggle & Climate Research Consortium',
    logoUrl: 'https://images.unsplash.com/photo-1534088568595-a066f410bcda?w=128&auto=format&fit=crop&q=80',
    description: 'Scientific machine learning competition to construct neural emulators for extreme climate events, localized heat anomalies, and atmospheric shifts using PyTorch.',
    officialUrl: 'https://www.kaggle.com/competitions/climx-main-track',
    registrationUrl: 'https://www.kaggle.com/competitions/climx-main-track',
    startDate: '2026-09-01',
    endDate: '2026-11-30',
    deadline: '2026-11-30',
    location: 'Online / Global',
    mode: 'online',
    geography: 'international',
    domains: ['AI/ML', 'Data Science', 'Research', 'Climate Tech'],
    skills: ['PyTorch', 'Machine Learning', 'Climate Science', 'Numerical Modeling'],
    eligibility: 'Open to all ML practitioners, students, and climate researchers worldwide.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Kaggle Research Competitions',
    featured: false,
    researchArea: 'Climate Emulators & Extreme Weather Modeling',
    institution: 'Kaggle Climate Consortium',
    funding: '$50,000 Research Prize Pool',
    positionType: 'Scientific ML Challenge',
    bookmarksCount: 280,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'research-cineca-open-hackathon',
    category: 'research',
    name: 'CINECA Open Hackathon: GPU & HPC Research',
    organization: 'CINECA × Open Hackathons',
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    description: 'Multi-day GPU and HPC development program with hands-on access to the Leonardo Tier-0 supercomputer and expert mentorship in GPU parallelization and code optimization.',
    officialUrl: 'https://www.openhackathons.org/s/siteevent/a0CUP00003NdHta2AF/se000459',
    registrationUrl: 'https://www.openhackathons.org/s/siteevent/a0CUP00003NdHta2AF/se000459',
    startDate: '2026-12-02',
    endDate: '2026-12-17',
    deadline: '2026-10-02',
    location: 'Hybrid (Online + CINECA, Italy)',
    mode: 'hybrid',
    geography: 'international',
    domains: ['Cloud Computing', 'AI/ML', 'Research', 'Data Science'],
    skills: ['CUDA', 'MPI', 'OpenACC', 'GPU Computing', 'C++', 'PyTorch', 'HPC'],
    eligibility: 'Researchers, developers, and students with computational or AI applications.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Open Hackathons & CINECA',
    featured: false,
    researchArea: 'GPU Computing, HPC, AI & Code Optimization',
    institution: 'CINECA Supercomputing Center',
    funding: 'Supercomputing Allocations on Leonardo & Mentorship',
    positionType: 'Research Team Allocation',
    bookmarksCount: 160,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },

  // ====================================================
  // --- OPEN SOURCE INITIATIVES (Stipends & Bounties) ---
  // ====================================================
  {
    id: 'opensource-kubecon-cncf-2026',
    category: 'opensource',
    name: 'KubeCon + CloudNativeCon NA 2026 — CNCF Travel & Diversity Grant',
    organization: 'Cloud Native Computing Foundation (CNCF) & Linux Foundation',
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    description: 'Travel reimbursement and registration scholarships to attend KubeCon in Salt Lake City, connecting active open-source contributors with core Kubernetes and cloud-native maintainers.',
    officialUrl: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/scholarships-travel-funding/',
    registrationUrl: 'https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/attend/scholarships-travel-funding/',
    startDate: '2026-11-12',
    endDate: '2026-11-15',
    deadline: '2026-10-04',
    location: 'Salt Lake City, Utah, USA',
    mode: 'offline',
    geography: 'international',
    domains: ['Cloud Computing', 'Open Source', 'Software Development'],
    skills: ['Kubernetes', 'Go', 'Docker', 'Cloud Native', 'Linux'],
    eligibility: 'Active community members and students who cannot afford attendance; emphasis on underrepresented groups.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Linux Foundation / CNCF',
    featured: true,
    role: 'CNCF Sponsored Scholar',
    programType: 'Scholarship & Travel Grant',
    stipend: 'Full Flights + Hotel + Free Conference Pass ($2,500+ value)',
    projectUrl: 'https://github.com/kubernetes/kubernetes',
    bookmarksCount: 390,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'opensource-esa-earthcode',
    category: 'opensource',
    name: 'ESA EarthCODE Open Science & FAIR Data Hackathon',
    organization: 'European Space Agency (ESA) & Open Science Community',
    logoUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=128&auto=format&fit=crop&q=80',
    description: '5-day open-science sprint building open Earth-system datasets, FAIR data cubes, ocean science algorithms, and carbon analysis workflows with open-source tools.',
    officialUrl: 'https://sciencehub.esa.int/event/esas-earthcode-hackathon-2026/',
    registrationUrl: 'https://eo4society.esa.int/event/earthcode-hackathon-2026/',
    startDate: '2026-11-30',
    endDate: '2026-12-04',
    deadline: '2026-10-16',
    location: 'ESA-ESRIN, Frascati (Rome), Italy',
    mode: 'offline',
    geography: 'international',
    domains: ['Data Science', 'Climate Tech', 'Open Source', 'Research'],
    skills: ['Python', 'Climate Modeling', 'Cloud Computing', 'EarthCODE', 'GeoTIFF'],
    eligibility: 'Earth scientists, data scientists, researchers, and open-source geospatial developers.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'ESA EO4Society Official',
    featured: false,
    role: 'Open Science Contributor',
    programType: 'Open Science / Data Cubes',
    stipend: 'ESA Open Science Fellowship & Publication',
    projectUrl: 'https://eo4society.esa.int/event/earthcode-hackathon-2026/',
    bookmarksCount: 185,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'opensource-gsoc-2026',
    category: 'opensource',
    name: 'Google Summer of Code (GSoC) 2026',
    organization: 'Google Open Source',
    logoUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=128&auto=format&fit=crop&q=80',
    description: 'Global program connecting student developers and contributors with open-source maintainers across Kubernetes, Linux, Chromium, PyTorch, and Apache on 12+ week mentored projects.',
    officialUrl: 'https://summerofcode.withgoogle.com/',
    registrationUrl: 'https://summerofcode.withgoogle.com/',
    startDate: '2026-09-15',
    endDate: '2027-04-30',
    deadline: '2026-11-01',
    location: 'Global / Virtual',
    mode: 'online',
    geography: 'international',
    domains: ['Open Source', 'Software Development', 'AI/ML', 'Cloud Computing'],
    skills: ['Git', 'Python', 'C++', 'Go', 'Rust', 'TypeScript'],
    eligibility: 'Students and beginner open-source developers worldwide aged 18+.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Google Open Source',
    featured: true,
    role: 'Open Source Contributor',
    programType: 'Mentorship & Contributor Program',
    stipend: '$1,500 – $6,600 Stipend (PPP-adjusted)',
    projectUrl: 'https://github.com/google/mentorship',
    bookmarksCount: 520,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'opensource-lfx-mentorship',
    category: 'opensource',
    name: 'LFX Mentorship Fall & Winter 2026',
    organization: 'The Linux Foundation',
    logoUrl: 'https://images.unsplash.com/photo-1618401471353-b98afee0b2eb?w=128&auto=format&fit=crop&q=80',
    description: 'Paid open source mentorship program working on core production repositories in Kubernetes, PyTorch Foundation, Hyperledger, CNCF, and RISC-V with seasoned maintainers.',
    officialUrl: 'https://lfx.linuxfoundation.org/tools/mentorship/',
    registrationUrl: 'https://lfx.linuxfoundation.org/tools/mentorship/',
    startDate: '2026-11-01',
    endDate: '2027-02-28',
    deadline: '2026-10-15',
    location: 'Remote / Global',
    mode: 'online',
    geography: 'international',
    domains: ['Open Source', 'Cloud Computing', 'AI/ML'],
    skills: ['Go', 'C++', 'Rust', 'Kubernetes', 'Linux Kernel'],
    eligibility: 'Developers and students globally interested in systems programming.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Linux Foundation Official',
    featured: true,
    role: 'LFX Mentee & OSS Contributor',
    programType: 'Production OSS Mentorship',
    stipend: '$3,000 – $6,600 Full Term Stipend',
    projectUrl: 'https://github.com/cncf',
    bookmarksCount: 440,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
  {
    id: 'opensource-outreachy-2026',
    category: 'opensource',
    name: 'Outreachy Diversity Tech Fellowship 2026',
    organization: 'Outreachy / Software Freedom Conservancy',
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80',
    description: 'Paid remote open-source internships for people subject to systemic bias and impacted by underrepresentation in the tech industry. Work on GNOME, Mozilla, Debian, and Wikimedia.',
    officialUrl: 'https://www.outreachy.org/',
    registrationUrl: 'https://www.outreachy.org/',
    startDate: '2026-12-01',
    endDate: '2027-03-01',
    deadline: '2026-10-15',
    location: 'Remote / Global',
    mode: 'online',
    geography: 'international',
    domains: ['Open Source', 'Software Development', 'Web Development'],
    skills: ['Git', 'Python', 'JavaScript', 'Documentation', 'Open Source'],
    eligibility: 'Anyone subject to systemic bias or underrepresented in tech.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Outreachy Official',
    featured: false,
    role: 'Outreachy Open Source Intern',
    programType: 'Diversity Open Source Fellowship',
    stipend: '$7,000 Total Stipend + $500 Travel Grant',
    projectUrl: 'https://github.com/outreachy',
    bookmarksCount: 310,
    createdAt: '2026-09-01T00:00:00.000Z',
    updatedAt: '2026-09-17T00:00:00.000Z',
  },
];
