import { Opportunity } from '../src/types';

export const initialOpportunities: Opportunity[] = [
  // --- HACKATHONS ---
  {
    id: 'hack-01',
    category: 'hackathon',
    name: 'HackMIT 2026',
    organization: 'Massachusetts Institute of Technology',
    logoUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=128&auto=format&fit=crop&q=80',
    description: 'MIT’s premier student-run global hackathon bringing together over 1,000 top undergraduate engineers, designers, and innovators for 36 hours of building groundbreaking AI, systems, and hardware projects.',
    officialUrl: 'https://hackmit.org',
    registrationUrl: 'https://hackmit.org/apply',
    startDate: '2026-09-25',
    endDate: '2026-09-27',
    deadline: '2026-09-18', // Closing very soon! (4 days away)
    location: 'Cambridge, MA, USA',
    mode: 'hybrid',
    geography: 'international',
    domains: ['AI/ML', 'Web Development', 'Robotics', 'Open Innovation'],
    skills: ['Python', 'TypeScript', 'PyTorch', 'Rust', 'Next.js'],
    eligibility: 'Currently enrolled undergraduate students from accredited universities worldwide. High school seniors may apply upon special petition.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'Official Organizer Portal',
    featured: true,
    teamSize: '1-4 Members',
    prizePool: '$45,000 + Venture Fast-Track',
    competitionType: 'Hackathon',
    bookmarksCount: 284,
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-09-01T12:00:00Z'
  },
  {
    id: 'hack-02',
    category: 'hackathon',
    name: 'Google Gemini Multimodal AI Sprint',
    organization: 'Google Developer Student Clubs & DeepMind',
    logoUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=128&auto=format&fit=crop&q=80',
    description: 'Global virtual challenge challenging teams to create innovative applications utilizing Gemini 3 multimodal capabilities, spatial audio, and agentic workflows.',
    officialUrl: 'https://developers.google.com/events/gemini-sprint',
    registrationUrl: 'https://developers.google.com/events/gemini-sprint/register',
    startDate: '2026-10-02',
    endDate: '2026-10-05',
    deadline: '2026-09-22',
    location: 'Global / Virtual',
    mode: 'online',
    geography: 'international',
    domains: ['AI/ML', 'Data Science', 'Healthcare', 'FinTech'],
    skills: ['Gemini API', 'Python', 'React', 'Cloud Run', 'Vector DBs'],
    eligibility: 'Open to all students, recent graduates, and independent software builders globally. Free entry.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Google Developers RSS',
    featured: true,
    teamSize: '1-3 Members',
    prizePool: '$75,000 in GCP Credits & Cash',
    competitionType: 'Innovation Challenge',
    bookmarksCount: 412,
    createdAt: '2026-08-20T08:00:00Z',
    updatedAt: '2026-09-10T14:30:00Z'
  },
  {
    id: 'hack-03',
    category: 'hackathon',
    name: 'NASA Space Apps Challenge 2026',
    organization: 'NASA Earth & Space Science Division',
    logoUrl: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=128&auto=format&fit=crop&q=80',
    description: 'The world’s largest annual space & science hackathon utilizing open NASA satellite, climate, and deep space exploration telemetry data to solve pressing terrestrial challenges.',
    officialUrl: 'https://www.spaceappschallenge.org',
    registrationUrl: 'https://www.spaceappschallenge.org/register',
    startDate: '2026-10-04',
    endDate: '2026-10-05',
    deadline: '2026-09-30',
    location: 'Worldwide (Local Chapters + Online)',
    mode: 'hybrid',
    geography: 'international',
    domains: ['Data Science', 'AI/ML', 'Robotics', 'Open Innovation'],
    skills: ['GIS', 'Python', 'Computer Vision', 'Data Visualization', 'D3.js'],
    eligibility: 'No restrictions. Anyone with a passion for problem-solving: students, scientists, developers, storytellers.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'NASA Space Apps Official',
    featured: false,
    teamSize: '2-6 Members',
    prizePool: 'Global NASA Winner Trophy & Kennedy Space Center Invitation',
    competitionType: 'Hackathon',
    bookmarksCount: 195,
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-09-05T11:00:00Z'
  },
  {
    id: 'hack-04',
    category: 'hackathon',
    name: 'ETHGlobal San Francisco',
    organization: 'ETHGlobal',
    logoUrl: 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1df?w=128&auto=format&fit=crop&q=80',
    description: 'Premier decentralized systems and smart contract engineering weekend bringing together top blockchain protocol architects, cryptography researchers, and frontend developers.',
    officialUrl: 'https://ethglobal.com/events/sanfrancisco2026',
    registrationUrl: 'https://ethglobal.com/apply',
    startDate: '2026-10-16',
    endDate: '2026-10-18',
    deadline: '2026-10-01',
    location: 'San Francisco, CA',
    mode: 'offline',
    geography: 'international',
    domains: ['Blockchain', 'Cybersecurity', 'FinTech', 'Web Development'],
    skills: ['Solidity', 'Rust', 'Zero-Knowledge Proofs', 'TypeScript', 'Ethers'],
    eligibility: 'Open to student and professional developers globally. Travel stipends available for accepted student teams.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'ETHGlobal Schedule',
    teamSize: '1-5 Members',
    prizePool: '$350,000 in Ecosystem Bounties',
    competitionType: 'Hackathon',
    bookmarksCount: 168,
    createdAt: '2026-08-25T14:00:00Z',
    updatedAt: '2026-09-08T16:00:00Z'
  },
  {
    id: 'hack-05',
    category: 'hackathon',
    name: 'CalHacks 13.0',
    organization: 'UC Berkeley',
    logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=128&auto=format&fit=crop&q=80',
    description: 'The world’s largest collegiate hackathon hosted at UC Berkeley’s historic Pauley Ballroom. Featuring venture mentors from Silicon Valley, top tech recruiters, and bleeding-edge hardware labs.',
    officialUrl: 'https://calhacks.io',
    registrationUrl: 'https://calhacks.io/apply',
    startDate: '2026-10-23',
    endDate: '2026-10-25',
    deadline: '2026-09-15', // Closing tomorrow / today!
    location: 'Berkeley, CA',
    mode: 'offline',
    geography: 'international',
    domains: ['AI/ML', 'Robotics', 'Healthcare', 'Software Development'],
    skills: ['Python', 'C++', 'PyTorch', 'ROS', 'React Native'],
    eligibility: 'All college/university students with valid student IDs.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'CalHacks Organizing Committee',
    teamSize: '1-4 Members',
    prizePool: '$100,000 + Y Combinator Interview Passes',
    competitionType: 'Hackathon',
    bookmarksCount: 310,
    createdAt: '2026-08-01T12:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z'
  },
  {
    id: 'hack-06',
    category: 'hackathon',
    name: 'Jane Street Electronic Trading Challenge',
    organization: 'Jane Street Capital',
    logoUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=128&auto=format&fit=crop&q=80',
    description: 'A 24-hour algorithmic trading competition where participants write high-frequency market-making bots that execute orders in a simulated live financial exchange.',
    officialUrl: 'https://www.janestreet.com/join-jane-street/programs-and-events',
    registrationUrl: 'https://www.janestreet.com/apply/etc',
    startDate: '2026-10-10',
    endDate: '2026-10-11',
    deadline: '2026-09-24',
    location: 'New York, NY & Online',
    mode: 'hybrid',
    geography: 'international',
    domains: ['FinTech', 'Software Development', 'Data Science'],
    skills: ['OCaml', 'Python', 'C++', 'Probability', 'Algorithms'],
    eligibility: 'Undergraduate and Master’s students graduating between Dec 2026 and June 2028.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Jane Street Campus Portal',
    teamSize: '2-3 Members',
    prizePool: '$30,000 Cash + Guaranteed Interview',
    competitionType: 'Coding Competition',
    bookmarksCount: 220,
    createdAt: '2026-08-28T09:00:00Z',
    updatedAt: '2026-09-09T18:00:00Z'
  },
  {
    id: 'hack-07',
    category: 'hackathon',
    name: 'Microsoft Imagine Cup 2027 Global Prelude',
    organization: 'Microsoft Corporation',
    logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&auto=format&fit=crop&q=80',
    description: 'Global student technology competition empowering student entrepreneurs to build high-impact tech startups with Azure AI, OpenAI models, and cloud computing.',
    officialUrl: 'https://imaginecup.microsoft.com',
    registrationUrl: 'https://imaginecup.microsoft.com/register',
    startDate: '2026-11-01',
    endDate: '2026-11-30',
    deadline: '2026-10-15',
    location: 'Worldwide / Virtual',
    mode: 'online',
    geography: 'international',
    domains: ['AI/ML', 'Healthcare', 'FinTech', 'Open Innovation'],
    skills: ['Azure', 'C#', 'Python', 'OpenAI API', 'Mobile Dev'],
    eligibility: 'Students aged 16+ enrolled in high school, college, or university.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Microsoft Student Hub',
    teamSize: '1-4 Members',
    prizePool: '$100,000 USD + Mentorship with Satya Nadella',
    competitionType: 'Ideathon',
    bookmarksCount: 350,
    createdAt: '2026-08-30T10:00:00Z',
    updatedAt: '2026-09-11T12:00:00Z'
  },
  {
    id: 'hack-08',
    category: 'hackathon',
    name: 'Hack The North 2026',
    organization: 'University of Waterloo & Techvibes',
    logoUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=128&auto=format&fit=crop&q=80',
    description: 'Canada’s biggest collegiate hackathon hosting 1,500 students from 30+ countries. 36 hours of non-stop mentorship, industry workshops, and gear.',
    officialUrl: 'https://hackthenorth.com',
    registrationUrl: 'https://hackthenorth.com/apply',
    startDate: '2026-09-18',
    endDate: '2026-09-20',
    deadline: '2026-09-10', // Closed
    location: 'Waterloo, ON, Canada',
    mode: 'offline',
    geography: 'international',
    domains: ['Web Development', 'Robotics', 'AI/ML', 'Cybersecurity'],
    skills: ['React', 'Node.js', 'Go', 'Computer Vision'],
    eligibility: 'High school, undergraduate, and graduate students worldwide.',
    status: 'closed',
    verificationStatus: 'verified',
    source: 'HackTheNorth Announcements',
    teamSize: '1-4 Members',
    prizePool: '$60,000 in Hardware & Cash',
    competitionType: 'Hackathon',
    bookmarksCount: 420,
    createdAt: '2026-07-20T08:00:00Z',
    updatedAt: '2026-09-11T09:00:00Z'
  },
  {
    id: 'hack-09',
    category: 'hackathon',
    name: 'OpenAI Developer Day Student Hack',
    organization: 'OpenAI',
    logoUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=128&auto=format&fit=crop&q=80',
    description: 'Build novel agentic architectures, real-time voice applications, and reasoning pipelines directly leveraging next-generation frontier intelligence models.',
    officialUrl: 'https://openai.com/devday',
    registrationUrl: 'https://openai.com/devday/student-hack',
    startDate: '2026-10-28',
    endDate: '2026-10-29',
    deadline: '2026-10-08',
    location: 'San Francisco, CA & Online Stream',
    mode: 'hybrid',
    geography: 'international',
    domains: ['AI/ML', 'Web Development', 'Software Development'],
    skills: ['OpenAI SDK', 'TypeScript', 'WebSockets', 'Vector DB'],
    eligibility: 'All university students enrolled in STEM or design degrees.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'OpenAI Dev Forum',
    teamSize: '1-3 Members',
    prizePool: '$80,000 in API Credits & Compute Hardware',
    competitionType: 'Hackathon',
    bookmarksCount: 512,
    createdAt: '2026-09-02T16:00:00Z',
    updatedAt: '2026-09-12T14:00:00Z'
  },
  {
    id: 'hack-10',
    category: 'hackathon',
    name: 'CyberDefense Inter-Collegiate CTF',
    organization: 'National Cyber Security Center & Carnegie Mellon Cylab',
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    description: 'Intense 48-hour offensive & defensive Capture The Flag (CTF) tournament covering binary exploitation, kernel reverse engineering, cryptographic attacks, and zero-day defense.',
    officialUrl: 'https://ctf.cylab.cmu.edu',
    registrationUrl: 'https://ctf.cylab.cmu.edu/register',
    startDate: '2026-10-17',
    endDate: '2026-10-19',
    deadline: '2026-09-29',
    location: 'Online / Distributed',
    mode: 'online',
    geography: 'national',
    domains: ['Cybersecurity', 'Software Development'],
    skills: ['GDB', 'Ghidra', 'Assembly x86_64', 'Wireshark', 'Python'],
    eligibility: 'Enrolled university students with .edu or institutional email verification.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'CTFTime.org',
    teamSize: '1-5 Members',
    prizePool: '$25,000 + SANS Security Training Certifications',
    competitionType: 'Coding Competition',
    bookmarksCount: 145,
    createdAt: '2026-08-18T11:00:00Z',
    updatedAt: '2026-09-07T13:00:00Z'
  },

  // --- INTERNSHIPS ---
  {
    id: 'intern-01',
    category: 'internship',
    name: 'AI Research Scientist Intern - Frontier Reasoning',
    organization: 'Google DeepMind',
    logoUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=128&auto=format&fit=crop&q=80',
    description: 'Join DeepMind’s core reasoning and agent research lab in London or Mountain View. You will collaborate with staff scientists on frontier reinforcement learning from human feedback, mathematical reasoning, and multimodal pretraining.',
    officialUrl: 'https://deepmind.google/careers/internships',
    registrationUrl: 'https://careers.google.com/jobs/results/deepmind-intern-2027',
    startDate: '2027-05-20',
    endDate: '2027-08-20',
    deadline: '2026-09-20', // Closing soon! (6 days left)
    location: 'Mountain View, CA / London, UK',
    mode: 'hybrid',
    geography: 'international',
    domains: ['AI/ML', 'Data Science', 'Research'],
    skills: ['PyTorch', 'JAX', 'Reinforcement Learning', 'Transformer Architectures', 'Linear Algebra'],
    eligibility: 'PhD or Master’s students in Computer Science, Applied Mathematics, or Physics with strong publication track record in NeurIPS/ICML/ICLR.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'DeepMind Careers Feed',
    featured: true,
    role: 'Research Scientist Intern',
    duration: '12-16 Weeks',
    stipend: '$10,200/month + Full Relocation & Housing',
    paidType: 'paid',
    bookmarksCount: 388,
    createdAt: '2026-08-10T12:00:00Z',
    updatedAt: '2026-09-02T15:00:00Z'
  },
  {
    id: 'intern-02',
    category: 'internship',
    name: 'Systems Infrastructure Engineering Intern',
    organization: 'Stripe',
    logoUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=128&auto=format&fit=crop&q=80',
    description: 'Architect and scale high-throughput, five-nines availability payment rails processing hundreds of billions of dollars. Work on distributed transaction ledgers, Kubernetes infrastructure, and observability tooling.',
    officialUrl: 'https://stripe.com/jobs/university',
    registrationUrl: 'https://stripe.com/apply/intern-swe',
    startDate: '2027-06-01',
    endDate: '2027-08-25',
    deadline: '2026-09-28',
    location: 'San Francisco, CA / Seattle, WA',
    mode: 'hybrid',
    geography: 'international',
    domains: ['Software Development', 'FinTech', 'Cybersecurity'],
    skills: ['Go', 'Java', 'Distributed Systems', 'PostgreSQL', 'Docker'],
    eligibility: 'Undergraduates graduating Winter 2026 or Spring 2027 pursuing CS, Computer Engineering, or related technical degrees.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Stripe University Recruiting',
    featured: true,
    role: 'Software Engineering Intern',
    duration: '12 Weeks',
    stipend: '$9,400/month + $2,500 Housing Stipend',
    paidType: 'paid',
    bookmarksCount: 295,
    createdAt: '2026-08-14T09:00:00Z',
    updatedAt: '2026-09-04T11:00:00Z'
  },
  {
    id: 'intern-03',
    category: 'internship',
    name: 'Autopilot Vision & Neural Network Intern',
    organization: 'Tesla Autopilot',
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    description: 'Train high-capacity 3D reconstruction and temporal occupancy networks running on Tesla HW4/HW5 inference chips. Solve dense scene understanding and trajectory planning in real-time.',
    officialUrl: 'https://www.tesla.com/careers/university',
    registrationUrl: 'https://www.tesla.com/careers/autopilot-intern',
    startDate: '2027-01-10',
    endDate: '2027-06-30',
    deadline: '2026-09-17', // Closing in 3 days!
    location: 'Palo Alto, CA',
    mode: 'offline',
    geography: 'national',
    domains: ['AI/ML', 'Robotics', 'Software Development'],
    skills: ['C++', 'CUDA', 'PyTorch', 'TensorRT', 'Computer Vision'],
    eligibility: 'Undergraduate or Graduate students with proven expertise in 3D computer vision and deep learning optimization.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'Tesla University Program',
    role: 'Neural Network Software Intern',
    duration: '6 Months Co-op',
    stipend: '$8,800/month + Corporate Housing',
    paidType: 'paid',
    bookmarksCount: 310,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-09-08T14:00:00Z'
  },
  {
    id: 'intern-04',
    category: 'internship',
    name: 'Quantitative Research & Strategy Intern',
    organization: 'Jane Street Capital',
    logoUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=128&auto=format&fit=crop&q=80',
    description: 'Work alongside quantitative traders and mathematicians to analyze massive historical financial market datasets, build predictive statistical models, and design automated trading strategies.',
    officialUrl: 'https://www.janestreet.com/join-jane-street/internships',
    registrationUrl: 'https://www.janestreet.com/apply/quant-intern',
    startDate: '2027-06-01',
    endDate: '2027-08-20',
    deadline: '2026-10-05',
    location: 'New York, NY / Hong Kong / London',
    mode: 'offline',
    geography: 'international',
    domains: ['FinTech', 'Data Science', 'AI/ML'],
    skills: ['Probability', 'Statistics', 'Python', 'Stochastic Calculus', 'OCaml'],
    eligibility: 'Enrolled undergraduate or graduate students with strong mathematical background (IMO/Putnam background strongly valued).',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Jane Street Portal',
    role: 'Quantitative Researcher Intern',
    duration: '10-12 Weeks',
    stipend: '$15,000/month + Luxury Housing & Chef-prepared Meals',
    paidType: 'paid',
    bookmarksCount: 460,
    createdAt: '2026-08-20T10:00:00Z',
    updatedAt: '2026-09-09T17:00:00Z'
  },
  {
    id: 'intern-05',
    category: 'internship',
    name: 'Full Stack Product Engineering Intern',
    organization: 'Vercel',
    logoUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=128&auto=format&fit=crop&q=80',
    description: 'Help build the next generation of Next.js, AI SDK, and edge compute platforms used by millions of developers across the globe. Focus on developer experience, rendering performance, and edge caching.',
    officialUrl: 'https://vercel.com/careers/university',
    registrationUrl: 'https://vercel.com/careers/swe-intern-2027',
    startDate: '2027-05-15',
    endDate: '2027-08-15',
    deadline: '2026-10-12',
    location: 'Remote (US, Canada, Europe)',
    mode: 'online',
    geography: 'international',
    domains: ['Web Development', 'Software Development'],
    skills: ['Next.js', 'React', 'TypeScript', 'Rust', 'Edge Functions'],
    eligibility: 'Enrolled university students graduating between Fall 2026 and Summer 2028.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Vercel Career Hub',
    role: 'Software Engineer Intern',
    duration: '12 Weeks',
    stipend: '$8,000/month + Remote Setup Budget',
    paidType: 'paid',
    bookmarksCount: 275,
    createdAt: '2026-08-22T13:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z'
  },
  {
    id: 'intern-06',
    category: 'internship',
    name: 'Kernel & Distributed Systems Intern',
    organization: 'Apple Platform Architecture',
    logoUrl: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=128&auto=format&fit=crop&q=80',
    description: 'Work on Darwin kernel internals, high-performance NVMe storage stacks, and low-level virtualization hypervisors running on Apple Silicon M-series processors.',
    officialUrl: 'https://jobs.apple.com/students',
    registrationUrl: 'https://jobs.apple.com/en-us/details/kernel-swe-intern',
    startDate: '2027-06-01',
    endDate: '2027-08-28',
    deadline: '2026-10-18',
    location: 'Cupertino, CA',
    mode: 'offline',
    geography: 'national',
    domains: ['Software Development', 'Cybersecurity', 'Robotics'],
    skills: ['C', 'Assembly ARM64', 'OS Internals', 'Concurrency', 'Debugging'],
    eligibility: 'B.S., M.S., or Ph.D. in Computer Science or Electrical Engineering.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Apple University Relations',
    role: 'Software Engineering Intern',
    duration: '12 Weeks',
    stipend: '$9,200/month + Subsidized Housing',
    paidType: 'paid',
    bookmarksCount: 210,
    createdAt: '2026-08-19T11:00:00Z',
    updatedAt: '2026-09-05T15:00:00Z'
  },
  {
    id: 'intern-07',
    category: 'internship',
    name: 'Robotics Perception & Control Intern',
    organization: 'Boston Dynamics',
    logoUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=128&auto=format&fit=crop&q=80',
    description: 'Develop dynamic balance, obstacle avoidance, and manipulation policies for Spot and Atlas humanoid robots working in industrial and disaster response environments.',
    officialUrl: 'https://bostondynamics.com/careers',
    registrationUrl: 'https://bostondynamics.com/apply/robotics-intern',
    startDate: '2027-05-15',
    endDate: '2027-08-30',
    deadline: '2026-10-25',
    location: 'Waltham, MA',
    mode: 'offline',
    geography: 'international',
    domains: ['Robotics', 'AI/ML', 'Software Development'],
    skills: ['C++', 'ROS 2', 'Control Systems', 'Kinematics', 'Reinforcement Learning'],
    eligibility: 'Undergraduate juniors, seniors, and graduate students in Robotics, Mechanical, or Computer Engineering.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Boston Dynamics Portal',
    role: 'Robotics Engineering Intern',
    duration: '14 Weeks',
    stipend: '$8,500/month + Relocation Allowance',
    paidType: 'paid',
    bookmarksCount: 340,
    createdAt: '2026-08-26T15:00:00Z',
    updatedAt: '2026-09-08T18:00:00Z'
  },
  {
    id: 'intern-08',
    category: 'internship',
    name: 'Hardware Accelerated AI Intern',
    organization: 'NVIDIA',
    logoUrl: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=128&auto=format&fit=crop&q=80',
    description: 'Optimize extreme-scale LLM training algorithms for next-gen Blackwell GPU clusters and NVLink network topologies. Implement custom CUDA kernels and GEMM routines.',
    officialUrl: 'https://www.nvidia.com/en-us/about-nvidia/careers/university-recruiting',
    registrationUrl: 'https://nvidia.wd5.myworkdayjobs.com/university_recruiting',
    startDate: '2027-05-25',
    endDate: '2027-08-20',
    deadline: '2026-09-30',
    location: 'Santa Clara, CA',
    mode: 'hybrid',
    geography: 'international',
    domains: ['AI/ML', 'Software Development', 'Data Science'],
    skills: ['CUDA', 'C++', 'PyTorch', 'GPU Architecture', 'MPI'],
    eligibility: 'Master’s or PhD students with strong parallel computing coursework or projects.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'NVIDIA University Board',
    role: 'Deep Learning System Intern',
    duration: '12 Weeks',
    stipend: '$9,800/month + Full Relocation & Stock Grant',
    paidType: 'paid',
    bookmarksCount: 395,
    createdAt: '2026-08-15T14:00:00Z',
    updatedAt: '2026-09-06T10:00:00Z'
  },
  {
    id: 'intern-09',
    category: 'internship',
    name: 'Data Science & Market Analytics Intern',
    organization: 'Spotify',
    logoUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=128&auto=format&fit=crop&q=80',
    description: 'Uncover insights across 600M+ active music and podcast streaming users. Build causal inference models and recommendation scoring algorithms powering Discover Weekly.',
    officialUrl: 'https://www.lifeatspotify.com/students',
    registrationUrl: 'https://www.lifeatspotify.com/apply/data-science-intern',
    startDate: '2027-06-01',
    endDate: '2027-08-15',
    deadline: '2026-10-10',
    location: 'New York, NY / Stockholm, Sweden',
    mode: 'hybrid',
    geography: 'international',
    domains: ['Data Science', 'AI/ML', 'Web Development'],
    skills: ['Python', 'SQL', 'A/B Testing', 'Causal Inference', 'BigQuery'],
    eligibility: 'Undergraduate or graduate students enrolled in statistics, data science, economics, or engineering.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'LifeAtSpotify RSS',
    role: 'Data Scientist Intern',
    duration: '10 Weeks',
    stipend: '$8,200/month + Housing',
    paidType: 'paid',
    bookmarksCount: 230,
    createdAt: '2026-08-24T12:00:00Z',
    updatedAt: '2026-09-07T16:00:00Z'
  },
  {
    id: 'intern-10',
    category: 'internship',
    name: 'Cybersecurity Threat Detection Intern',
    organization: 'CrowdStrike Falcon Labs',
    logoUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=128&auto=format&fit=crop&q=80',
    description: 'Analyze nation-state cyber threat actors, reverse engineer evasive ransomware payloads, and train automated anomaly detection graph models on endpoint telemetry.',
    officialUrl: 'https://www.crowdstrike.com/careers/university',
    registrationUrl: 'https://crowdstrike.com/apply/security-intern-2027',
    startDate: '2027-05-20',
    endDate: '2027-08-15',
    deadline: '2026-10-22',
    location: 'Austin, TX / Remote',
    mode: 'online',
    geography: 'national',
    domains: ['Cybersecurity', 'AI/ML', 'Software Development'],
    skills: ['Reverse Engineering', 'Python', 'Network Security', 'Threat Hunting', 'SIEM'],
    eligibility: 'Undergraduate or master’s students majoring in Cybersecurity, Computer Science, or Information Assurance.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'CrowdStrike Campus Recruiting',
    role: 'Threat Intelligence Intern',
    duration: '12 Weeks',
    stipend: '$7,800/month + Remote Equipment Bonus',
    paidType: 'paid',
    bookmarksCount: 185,
    createdAt: '2026-08-27T08:00:00Z',
    updatedAt: '2026-09-09T11:00:00Z'
  },

  // --- RESEARCH OPPORTUNITIES ---
  {
    id: 'res-01',
    category: 'research',
    name: 'Foundation Model Alignment & Safety Fellowship',
    organization: 'Stanford University (CRFM)',
    logoUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=128&auto=format&fit=crop&q=80',
    description: 'Conduct foundational research at Stanford Center for Research on Foundation Models (CRFM) under leading faculty. Projects investigate mechanistic interpretability, red-teaming safety evaluations, and hallucination reduction in reasoning models.',
    officialUrl: 'https://crfm.stanford.edu/fellowship',
    registrationUrl: 'https://crfm.stanford.edu/apply-fellowship-2027',
    startDate: '2027-01-08',
    endDate: '2027-06-15',
    deadline: '2026-09-21', // 7 days left!
    location: 'Stanford, CA, USA',
    mode: 'hybrid',
    geography: 'international',
    domains: ['Research', 'AI/ML', 'Cybersecurity'],
    skills: ['PyTorch', 'Transformer Interpretability', 'Mathematical Proofs', 'Empirical NLP'],
    eligibility: 'Undergraduates, Master’s students, or recent graduates intending to pursue PhD research. Open globally.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'Stanford CRFM Announcements',
    featured: true,
    professor: 'Prof. Percy Liang & Prof. Dan Jurafsky',
    institution: 'Stanford University',
    researchArea: 'Foundation Models, Alignment & Empirical NLP',
    funding: 'Fully Funded ($32,000 Stipend + Campus Housing Grant)',
    positionType: 'Fellowship',
    bookmarksCount: 420,
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-09-03T14:00:00Z'
  },
  {
    id: 'res-02',
    category: 'research',
    name: 'CERN Openlab Summer Student Research Program',
    organization: 'CERN (European Organization for Nuclear Research)',
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    description: 'Work with the world’s leading particle physicists and computer engineers at CERN in Geneva. Develop novel high-performance data processing pipelines and quantum machine learning algorithms for Large Hadron Collider (LHC) particle collision data.',
    officialUrl: 'https://openlab.cern/summer-student-programme',
    registrationUrl: 'https://careers.cern/job/openlab-student-2027',
    startDate: '2027-06-15',
    endDate: '2027-08-25',
    deadline: '2026-10-02',
    location: 'Geneva, Switzerland',
    mode: 'offline',
    geography: 'international',
    domains: ['Research', 'Data Science', 'AI/ML', 'Software Development'],
    skills: ['C++', 'High Performance Computing', 'ROOT Data Framework', 'Quantum Algorithms', 'Python'],
    eligibility: 'Bachelor or Master students having completed at least 3 years of full-time university studies in Computer Science or Physics.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'CERN Official Bulletin',
    featured: true,
    professor: 'Dr. Alberto Di Meglio (Head of CERN openlab)',
    institution: 'CERN',
    researchArea: 'Exascale High Energy Physics Computing',
    funding: 'CHF 90/day living allowance + Comprehensive Health Insurance & Travel',
    positionType: 'Fellowship',
    bookmarksCount: 360,
    createdAt: '2026-08-16T11:00:00Z',
    updatedAt: '2026-09-06T12:00:00Z'
  },
  {
    id: 'res-03',
    category: 'research',
    name: 'MIT CSAIL Distributed Systems Research Assistantship',
    organization: 'MIT Computer Science & Artificial Intelligence Laboratory',
    logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=128&auto=format&fit=crop&q=80',
    description: 'Join the Parallel & Distributed Operating Systems group at CSAIL. Research fault-tolerant consensus protocols, formal verification of distributed key-value stores, and decentralized state machines.',
    officialUrl: 'https://www.csail.mit.edu/research',
    registrationUrl: 'https://urop.mit.edu/apply-csail-distributed',
    startDate: '2027-02-01',
    endDate: '2027-05-30',
    deadline: '2026-09-26',
    location: 'Cambridge, MA',
    mode: 'hybrid',
    geography: 'national',
    domains: ['Research', 'Software Development', 'Cybersecurity'],
    skills: ['Go', 'Rust', 'Raft/Paxos Consensus', 'TLA+ Formal Methods', 'Linux Kernel'],
    eligibility: 'Undergraduate or master’s students with strong operating systems and concurrent programming background.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'MIT CSAIL Faculty Board',
    professor: 'Prof. Robert Morris & Prof. Frans Kaashoek',
    institution: 'MIT CSAIL',
    researchArea: 'Formal Verification of Distributed Systems',
    funding: 'Hourly Academic Research Rate ($28/hr, 20 hrs/week) or Full Tuition Credit',
    positionType: 'Research Assistant',
    bookmarksCount: 290,
    createdAt: '2026-08-18T14:00:00Z',
    updatedAt: '2026-09-07T10:00:00Z'
  },
  {
    id: 'res-04',
    category: 'research',
    name: 'Berkeley AI Research (BAIR) Visiting Student Scholar',
    organization: 'UC Berkeley BAIR Lab',
    logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=128&auto=format&fit=crop&q=80',
    description: 'Focus on robot learning, physical dexterity, and deep visual-tactile reinforcement learning. Experiment with physical robotic arms and simulated IsaacGym physics engines.',
    officialUrl: 'https://bair.berkeley.edu',
    registrationUrl: 'https://bair.berkeley.edu/admissions/visiting-scholars',
    startDate: '2027-01-15',
    endDate: '2027-06-30',
    deadline: '2026-10-14',
    location: 'Berkeley, CA',
    mode: 'offline',
    geography: 'international',
    domains: ['Research', 'Robotics', 'AI/ML'],
    skills: ['PyTorch', 'Isaac Gym / MuJoCo', 'Reinforcement Learning', 'Trajectory Optimization'],
    eligibility: 'Undergraduate seniors and graduate students globally. Prior ML coursework required.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'BAIR Academic Bulletin',
    professor: 'Prof. Sergey Levine & Prof. Pieter Abbeel',
    institution: 'UC Berkeley',
    researchArea: 'Embodied AI & Robotic Motor Control',
    funding: '$4,200/month research grant + compute cluster access',
    positionType: 'Fellowship',
    bookmarksCount: 380,
    createdAt: '2026-08-21T10:00:00Z',
    updatedAt: '2026-09-08T15:00:00Z'
  },
  {
    id: 'res-05',
    category: 'research',
    name: 'Harvard Quantum Computing & Optics Research Project',
    organization: 'Harvard Quantum Initiative (HQI)',
    logoUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=128&auto=format&fit=crop&q=80',
    description: 'Investigate neutral atom arrays, Rydberg quantum simulators, and topological quantum error correction codes. Bridge theoretical quantum information theory with experimental laser cooling apparatus.',
    officialUrl: 'https://quantum.harvard.edu',
    registrationUrl: 'https://quantum.harvard.edu/student-research-application',
    startDate: '2027-06-01',
    endDate: '2027-08-25',
    deadline: '2026-10-30',
    location: 'Cambridge, MA',
    mode: 'offline',
    geography: 'international',
    domains: ['Research', 'AI/ML', 'Software Development'],
    skills: ['Quantum Information', 'Qiskit / Cirq', 'Python', 'Linear Algebra', 'Optics Lab Skills'],
    eligibility: 'Students majoring in Physics, Math, Electrical Engineering, or CS with quantum mechanics coursework.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Harvard Quantum Initiative Portal',
    professor: 'Prof. Mikhail Lukin & Prof. Susanne Yelin',
    institution: 'Harvard University',
    researchArea: 'Neutral Atom Quantum Simulation & Quantum Error Correction',
    funding: '$7,000 Summer Research Stipend + Harvard Yard Housing',
    positionType: 'Open Research Project',
    bookmarksCount: 245,
    createdAt: '2026-08-25T13:00:00Z',
    updatedAt: '2026-09-09T14:00:00Z'
  },
  {
    id: 'res-06',
    category: 'research',
    name: 'Carnegie Mellon Robotics Institute Summer Scholars (RISS)',
    organization: 'Carnegie Mellon University Robotics Institute',
    logoUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=128&auto=format&fit=crop&q=80',
    description: 'World-renowned 11-week intensive summer research immersion program pairing top undergraduates with CMU robotics faculty to author academic publications and build autonomous systems.',
    officialUrl: 'https://riss.ri.cmu.edu',
    registrationUrl: 'https://riss.ri.cmu.edu/apply-2027',
    startDate: '2027-06-01',
    endDate: '2027-08-15',
    deadline: '2026-11-10',
    location: 'Pittsburgh, PA',
    mode: 'offline',
    geography: 'international',
    domains: ['Research', 'Robotics', 'AI/ML'],
    skills: ['ROS', 'C++', 'Computer Vision', 'State Estimation', 'SLAM'],
    eligibility: 'Undergraduate students worldwide from diverse backgrounds. Women and underrepresented minorities in STEM strongly encouraged to apply.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'CMU Robotics Institute Outreach',
    professor: 'Dr. John Dolan (Director RISS) & RI Faculty',
    institution: 'Carnegie Mellon University',
    researchArea: 'Autonomous Navigation, SLAM & Field Robotics',
    funding: 'Full scholarship covering lodging, food, travel, and research supplies ($6,500 total value)',
    positionType: 'Fellowship',
    bookmarksCount: 310,
    createdAt: '2026-08-29T10:00:00Z',
    updatedAt: '2026-09-10T16:00:00Z'
  },
  {
    id: 'res-07',
    category: 'research',
    name: 'Oxford Computational Neuroscience & Brain-Computer Research',
    organization: 'University of Oxford Department of Physiology',
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    description: 'Decipher motor cortex neural spiking signals during motor planning using high-density Neuropixels electrophysiology recordings and recurrent neural network modeling.',
    officialUrl: 'https://www.dpag.ox.ac.uk/research',
    registrationUrl: 'https://www.ox.ac.uk/admissions/graduate/research-internships',
    startDate: '2027-01-20',
    endDate: '2027-07-20',
    deadline: '2026-10-15',
    location: 'Oxford, United Kingdom',
    mode: 'hybrid',
    geography: 'international',
    domains: ['Research', 'AI/ML', 'Healthcare', 'Data Science'],
    skills: ['Neural Data Analysis', 'Python', 'Signal Processing', 'PyTorch', 'Neurobiology'],
    eligibility: 'Undergraduate seniors, master’s students, or clinical medical scholars.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'Oxford DPAG Research Notices',
    professor: 'Prof. Timothy Behrens & Prof. Gero Miesenböck',
    institution: 'University of Oxford',
    researchArea: 'Neural Dynamics & Machine-Assisted Brain Interfaces',
    funding: '£18,000 annual research bursary + College dining rights',
    positionType: 'Research Assistant',
    bookmarksCount: 260,
    createdAt: '2026-08-23T11:00:00Z',
    updatedAt: '2026-09-08T12:00:00Z'
  },
  {
    id: 'res-08',
    category: 'research',
    name: 'Max Planck Institute for Software Systems Student Fellowship',
    organization: 'Max Planck Society (MPI-SWS)',
    logoUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=128&auto=format&fit=crop&q=80',
    description: 'Collaborate with world-class faculty in Saarbrücken and Kaiserslautern on computer security, provably correct cryptographic protocols, and algorithmic fairness in decision systems.',
    officialUrl: 'https://www.mpi-sws.org/research-internships',
    registrationUrl: 'https://www.mpi-sws.org/apply-fellowship-2027',
    startDate: '2027-05-01',
    endDate: '2027-08-31',
    deadline: '2026-10-20',
    location: 'Saarbrücken, Germany',
    mode: 'offline',
    geography: 'international',
    domains: ['Research', 'Cybersecurity', 'Software Development'],
    skills: ['Formal Verification', 'Rust', 'Coq', 'Information Theory', 'Cryptography'],
    eligibility: 'Enrolled Bachelor or Master students in Computer Science or Mathematics from any university globally.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'MPI-SWS Global Bulletin',
    professor: 'Prof. Peter Druschel & Prof. Rupak Majumdar',
    institution: 'Max Planck Institute for Software Systems',
    researchArea: 'Secure & Trustworthy Computing Systems',
    funding: '€1,200/month stipend + Free student residence apartment & travel costs',
    positionType: 'Fellowship',
    bookmarksCount: 215,
    createdAt: '2026-08-26T09:00:00Z',
    updatedAt: '2026-09-09T13:00:00Z'
  },
  {
    id: 'res-09',
    category: 'research',
    name: 'Princeton NLP & Reasoning Lab Research Assistant',
    organization: 'Princeton University Computer Science',
    logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=128&auto=format&fit=crop&q=80',
    description: 'Investigate tree-of-thought reasoning, multi-step logical deduction, and tool augmentation for autonomous coding agents under leading faculty in Princeton, NJ.',
    officialUrl: 'https://nlp.cs.princeton.edu',
    registrationUrl: 'https://cs.princeton.edu/apply-ra',
    startDate: '2027-02-01',
    endDate: '2027-06-01',
    deadline: '2026-09-19', // Closing in 5 days!
    location: 'Princeton, NJ',
    mode: 'hybrid',
    geography: 'national',
    domains: ['Research', 'AI/ML', 'Software Development'],
    skills: ['Python', 'HuggingFace', 'PyTorch', 'Symbolic Reasoning', 'Benchmarks'],
    eligibility: 'Undergraduate juniors/seniors with strong software engineering and machine learning proficiency.',
    status: 'closing_soon',
    verificationStatus: 'verified',
    source: 'Princeton CS Department',
    professor: 'Prof. Danqi Chen & Prof. Karthik Narasimhan',
    institution: 'Princeton University',
    researchArea: 'Reasoning, Agentic Workflows & Natural Language Understanding',
    funding: '$6,000 semester fellowship + compute cluster credits',
    positionType: 'Research Assistant',
    bookmarksCount: 350,
    createdAt: '2026-08-15T09:00:00Z',
    updatedAt: '2026-09-04T17:00:00Z'
  },
  {
    id: 'res-10',
    category: 'research',
    name: 'Allen Institute for AI (AI2) Pre-doctoral Fellowship',
    organization: 'Allen Institute for Artificial Intelligence',
    logoUrl: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=128&auto=format&fit=crop&q=80',
    description: 'One-year immersive research fellowship aimed at students planning to apply to top PhD programs. Work on OLMo (Open Language Model) architectures, multimodal reasoning, and open science datasets.',
    officialUrl: 'https://allenai.org/careers/predoc',
    registrationUrl: 'https://allenai.org/apply/predoc-2027',
    startDate: '2027-06-15',
    endDate: '2028-06-15',
    deadline: '2026-10-31',
    location: 'Seattle, WA',
    mode: 'hybrid',
    geography: 'international',
    domains: ['Research', 'AI/ML', 'Data Science'],
    skills: ['PyTorch', 'Distributed Training', 'Dataset Curation', 'Open Science Evaluation'],
    eligibility: 'Graduating seniors or Master’s recipients planning to enter PhD programs in 2028.',
    status: 'open',
    verificationStatus: 'verified',
    source: 'AI2 Careers RSS',
    professor: 'Dr. Ali Farhadi & OLMo Core Team',
    institution: 'Allen Institute for AI (AI2)',
    researchArea: 'Open Foundation Models & Scientific AI',
    funding: '$95,000 annual salary + Comprehensive Benefits + Travel to NeurIPS/ACL',
    positionType: 'Fellowship',
    bookmarksCount: 470,
    createdAt: '2026-08-30T14:00:00Z',
    updatedAt: '2026-09-11T16:00:00Z'
  },
  {
    id: 'pending-ai-1',
    category: 'hackathon',
    name: 'Agentic AI Systems & Multi-Agent Hackathon',
    organization: 'Anthropic & AWS',
    logoUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=128&auto=format&fit=crop&q=80',
    description: 'Construct cooperative multi-agent workflows solving complex reasoning problems using Claude 3.7 Sonnet and Amazon Bedrock.',
    officialUrl: 'https://devpost.com/hackathons/agentic-aws-anthropic',
    registrationUrl: 'https://devpost.com/hackathons/agentic-aws-anthropic/register',
    startDate: '2026-10-10',
    endDate: '2026-10-12',
    deadline: '2026-09-26',
    location: 'Virtual Worldwide',
    mode: 'online',
    geography: 'international',
    domains: ['AI/ML', 'Cloud', 'Software Development'],
    skills: ['Python', 'Multi-Agent', 'Claude API', 'Bedrock'],
    eligibility: 'Open to university students and independent developers worldwide.',
    status: 'open',
    verificationStatus: 'pending',
    source: 'Automated Web & Devpost Discovery Agent',
    confidence: 0.94,
    teamSize: '1-4 Members',
    prizePool: '$65,000 + AWS Credits',
    competitionType: 'Hackathon',
    bookmarksCount: 0,
    createdAt: '2026-09-14T08:30:00Z',
    updatedAt: '2026-09-14T08:30:00Z'
  },
  {
    id: 'pending-ai-2',
    category: 'research',
    name: 'NSF REU: Scalable Cyber-Physical Security for Smart Grids',
    organization: 'Georgia Institute of Technology',
    logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=128&auto=format&fit=crop&q=80',
    description: '10-week summer undergraduate research experience in cybersecurity, automated intrusion detection, and SCADA protection for power grids.',
    officialUrl: 'https://ece.gatech.edu/nsf-reu-smartgrids',
    registrationUrl: 'https://ece.gatech.edu/nsf-reu-smartgrids/apply',
    startDate: '2027-05-25',
    endDate: '2027-08-01',
    deadline: '2026-10-02',
    location: 'Atlanta, GA',
    mode: 'offline',
    geography: 'national',
    domains: ['Cybersecurity', 'Research', 'Electronics'],
    skills: ['Python', 'C++', 'SCADA', 'Intrusion Detection'],
    eligibility: 'Undergraduate students who are US citizens or permanent residents enrolled in STEM programs.',
    status: 'open',
    verificationStatus: 'pending',
    source: 'NSF REU Public Grant Feed',
    confidence: 0.91,
    professor: 'Prof. Raheem Beyah',
    institution: 'Georgia Institute of Technology',
    researchArea: 'Cyber-Physical Systems & Grid Security',
    funding: '$7,000 summer stipend + On-campus housing & meal plan',
    positionType: 'Fellowship',
    bookmarksCount: 0,
    createdAt: '2026-09-14T09:15:00Z',
    updatedAt: '2026-09-14T09:15:00Z'
  },
  // --- PAST DUE OPPORTUNITIES (For Admin Past Dues view & deadline management) ---
  {
    id: 'past-hack-01',
    category: 'hackathon',
    name: 'PennApps XXVI Global Hackathon',
    organization: 'University of Pennsylvania',
    logoUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=128&auto=format&fit=crop&q=80',
    description: 'The nation’s original collegiate hackathon held in Philadelphia, focused on hardware builds, web engineering, and enterprise AI.',
    officialUrl: 'https://pennapps.com',
    registrationUrl: 'https://pennapps.com/apply',
    startDate: '2026-09-11',
    endDate: '2026-09-13',
    deadline: '2026-09-02',
    location: 'Philadelphia, PA',
    mode: 'offline',
    geography: 'national',
    domains: ['AI/ML', 'Robotics', 'Web Development'],
    skills: ['Python', 'C++', 'React', 'Hardware'],
    eligibility: 'All collegiate students.',
    status: 'closed',
    verificationStatus: 'verified',
    source: 'PennApps Organizing Board',
    teamSize: '1-4 Members',
    prizePool: '$30,000 in Prizes',
    competitionType: 'Hackathon',
    bookmarksCount: 88,
    createdAt: '2026-08-01T10:00:00Z',
    updatedAt: '2026-09-03T12:00:00Z'
  },
  {
    id: 'past-intern-01',
    category: 'internship',
    name: 'Quantitative Technology Summer Analyst',
    organization: 'Morgan Stanley',
    logoUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=128&auto=format&fit=crop&q=80',
    description: 'Build algorithmic execution tools, low-latency risk pricing engines, and real-time data visualizers for institutional fixed income desks.',
    officialUrl: 'https://morganstanley.com/careers',
    registrationUrl: 'https://morganstanley.tal.net/apply/quant',
    startDate: '2027-06-01',
    endDate: '2027-08-15',
    deadline: '2026-08-28',
    location: 'New York, NY',
    mode: 'offline',
    geography: 'national',
    domains: ['FinTech', 'Data Science', 'Software Development'],
    skills: ['C++', 'Python', 'Stochastic Calculus', 'SQL'],
    eligibility: 'Undergraduate students graduating in Dec 2027 or May 2028.',
    status: 'closed',
    verificationStatus: 'verified',
    source: 'Morgan Stanley Campus Recruiting',
    role: 'Quantitative Technology Analyst',
    duration: '10 Weeks',
    stipend: '$11,000/month',
    paidType: 'paid',
    bookmarksCount: 142,
    createdAt: '2026-07-20T10:00:00Z',
    updatedAt: '2026-08-29T10:00:00Z'
  },
  {
    id: 'past-res-01',
    category: 'research',
    name: 'MIT CSAIL Vision & Language Grant Fellowship',
    organization: 'MIT CSAIL',
    logoUrl: 'https://images.unsplash.com/photo-1541829070764-84a7d30dd3f3?w=128&auto=format&fit=crop&q=80',
    description: 'Undergraduate research on cross-modal video reasoning and grounding large multimodal models with physical robotic sensor streams.',
    officialUrl: 'https://csail.mit.edu',
    registrationUrl: 'https://csail.mit.edu/apply-fellowship',
    startDate: '2026-09-20',
    endDate: '2027-01-15',
    deadline: '2026-09-06',
    location: 'Cambridge, MA',
    mode: 'hybrid',
    geography: 'international',
    domains: ['Research', 'AI/ML'],
    skills: ['PyTorch', 'Vision-Language Models', 'Computer Vision'],
    eligibility: 'Undergraduate researchers with experience in deep learning frameworks.',
    status: 'closed',
    verificationStatus: 'verified',
    source: 'MIT CSAIL Fellowship Feed',
    professor: 'Prof. Phillip Isola',
    institution: 'MIT CSAIL',
    researchArea: 'Vision & Learning Lab',
    funding: '$6,500 semester grant',
    positionType: 'Fellowship',
    bookmarksCount: 95,
    createdAt: '2026-07-25T14:00:00Z',
    updatedAt: '2026-09-07T12:00:00Z'
  }
];
